struct SampleData {
    static let mockTasks: [UserTask] = [
        UserTask(
            id: 1,
            headline: "Plan summer vacation",
            description: "Rent a plane, book airplane parking, book hotel, plan adventures, pack suitcase",
            isCompleted: false
        ),
        UserTask(
            id: 2,
            headline: "Pick up Too Good to Go order",
            description: "Bossens Bageri og konditori. Between 17:30 - 18:00. Østerbrogade 132, 2100 København Ø",
            isCompleted: false
        ),
        UserTask(
            id: 3,
            headline: "Prepare presentation for Monday meeting",
            description: "Create slides, review key points, rehearse presentation, print handouts",
            isCompleted: false
        ),
        UserTask(
            id: 4,
            headline: "Clean the kitchen",
            description: "Wipe countertops, clean the sink, empty the dishwasher, sweep and mop the floor",
            isCompleted: true
        ),
        UserTask(
            id: 5,
            headline: "Buy groceries",
            description: "Milk, bread, eggs, chicken breast, pasta, and fresh vegetables",
            isCompleted: false
        )
    ]
}
